# Generated by Django 5.2.8 on 2025-12-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
