# Generated by Django 5.2.8 on 2025-12-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='UserName'),
            preserve_default=False,
        ),
    ]
