# Generated by Django 5.2.8 on 2025-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Заголовок')),
                ('content', models.TextField()),
                ('prev_image', models.ImageField(null=True, upload_to='images/', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('publication_flag', models.BooleanField(default=False, null=True, verbose_name='Изображение')),
                ('number_of_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'db_table': 'blog_records',
                'ordering': ['title'],
            },
        ),
    ]
