# Generated by Django 5.2.8 on 2026-01-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_unpublish_product', 'Can unpublish product'), ('cant_unpublish_product', "Can't unpublish product")], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.BooleanField(default=False, verbose_name='Статус публикации'),
            preserve_default=False,
        ),
    ]
