# Generated by Django 5.2.8 on 2026-01-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_product_publish_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
